# Generated by Django 4.0.3 on 2023-06-21 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('status', models.CharField(blank=True, choices=[('RQ', 'REQUESTED'), ('APV', 'APPROVED'), ('OP', 'OPENED'), ('INIT', 'INITIATED'), ('LK', 'LOCKED'), ('CD', 'CLOSED')], max_length=50, null=True)),
                ('total_balance', models.DecimalField(blank=True, decimal_places=1, max_digits=19, null=True)),
                ('channel_address', models.CharField(blank=True, max_length=200)),
                ('status_expiry', models.DateTimeField(blank=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('channel', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='channelstate.channel')),
                ('locked_recipient_bal', models.DecimalField(blank=True, decimal_places=1, max_digits=19, null=True)),
                ('locked_initiator_bal', models.DecimalField(blank=True, decimal_places=1, max_digits=19, null=True)),
                ('latest_recipient_bal', models.DecimalField(blank=True, decimal_places=1, max_digits=19, null=True)),
                ('latest_initiator_bal', models.DecimalField(blank=True, decimal_places=1, max_digits=19, null=True)),
                ('ptp_recipient_bal', models.DecimalField(blank=True, decimal_places=1, max_digits=19, null=True)),
                ('ptp_initiator_bal', models.DecimalField(blank=True, decimal_places=1, max_digits=19, null=True)),
                ('topup_recipient_bal', models.DecimalField(blank=True, decimal_places=1, max_digits=19, null=True)),
                ('topup_initiator_bal', models.DecimalField(blank=True, decimal_places=1, max_digits=19, null=True)),
            ],
        ),
    ]
