# Generated by Django 4.0.3 on 2023-07-12 16:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channelstate', '0003_channel_closed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='total_balance',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0'), max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='latest_initiator_bal',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0'), max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='latest_recipient_bal',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0'), max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='locked_initiator_bal',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0'), max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='locked_recipient_bal',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0'), max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='ptp_initiator_bal',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0'), max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='ptp_recipient_bal',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0'), max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='topup_initiator_bal',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0'), max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='topup_recipient_bal',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0'), max_digits=19, null=True),
        ),
    ]
