# Generated by Django 4.0.3 on 2023-06-26 01:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('channelstate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PtpGlobal',
            fields=[
                ('path_array', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=300, null=True), default=list, size=None)),
                ('ptp_global_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=1, max_digits=19, null=True)),
                ('status', models.CharField(blank=True, choices=[('PD', 'PENDING'), ('SS', 'SUCCESS'), ('FL', 'FAILED')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PtpLocal',
            fields=[
                ('ptp_local_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=1, max_digits=19, null=True)),
                ('status', models.CharField(blank=True, choices=[('PD', 'PENDING'), ('SS', 'SUCCESS'), ('FL', 'FAILED')], max_length=50, null=True)),
                ('local_nonce', models.IntegerField(blank=True, null=True)),
                ('ptp_bonus', models.DecimalField(blank=True, decimal_places=17, max_digits=19, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TopupReceipt',
            fields=[
                ('topup_receipt_id', models.AutoField(primary_key=True, serialize=False)),
                ('local_nonce', models.IntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=1, max_digits=19, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLocal',
            fields=[
                ('transaction_local_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(blank=True, decimal_places=1, max_digits=19, null=True)),
                ('status', models.CharField(blank=True, choices=[('PD', 'PENDING'), ('SS', 'SUCCESS'), ('FL', 'FAILED')], max_length=50, null=True)),
                ('sender_sig', models.CharField(blank=True, max_length=300, null=True)),
                ('receiver_sig', models.CharField(blank=True, max_length=300, null=True)),
                ('local_nonce', models.IntegerField(blank=True, null=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='channelstate.ledger')),
            ],
        ),
    ]
