# Generated by Django 4.0.3 on 2023-07-12 16:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptpglobal',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0'), max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='ptplocal',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0'), max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='ptplocal',
            name='ptp_bonus',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0'), max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='topupreceipt',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0'), max_digits=19, null=True),
        ),
        migrations.AlterField(
            model_name='transactionlocal',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=1, default=Decimal('0'), max_digits=19, null=True),
        ),
    ]
